### ISSUE TITLE
مشکل در ریسپانسیو بودن

### ISSUE THREAD

**Issue by SMSadegh19** [PersianHodHod/wealth-in-pixels#10]
<div dir="rtl">

یه سری جاها فک کنم توی موبایل مشکل داشته باشه. فعلا اینو پیدا کردم.

![image](https://user-images.githubusercontent.com/45296858/137645713-e3427f71-236d-4eb5-9371-4388ed742140.png)

</div>

**Comment by HKalbasi** [comment]
توی سایت اصلی خراب نیست؟

**Comment by SMSadegh19** [comment]
نمی‌دونم.

**Comment by HKalbasi** [comment]
نمی تونم باز تولیدش کنم. رو گوشی من درسته. مرورگرت قدیمی نیست؟
